using Core;
using Core.Config;
using Discord;
using Discord.Interactions;
using Discord.WebSocket;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;

namespace GaryBotServer.Discord;

// File generated by ChatGPT - Can't stand sifting through API documentation
public class DiscordBotService : BackgroundService, IBuildNotifications
{
    private readonly IServiceProvider _services;
    private readonly DiscordOptions _options;
    private readonly DiscordSocketClient _client;
    private readonly InteractionService _interactions;

    public DiscordBotService(
        IServiceProvider services,
        IOptions<DiscordOptions> options)
    {
        _services = services;
        _options = options.Value;

        var config = new DiscordSocketConfig
        {
            GatewayIntents = GatewayIntents.Guilds
        };

        _client = new DiscordSocketClient(config);
        _interactions = new InteractionService(_client.Rest);

        _client.Log += LogAsync;
        _interactions.Log += LogAsync;

        _client.Ready += OnReadyAsync;
        _client.InteractionCreated += OnInteractionCreatedAsync;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        if (string.IsNullOrWhiteSpace(_options.Token))
            throw new InvalidOperationException("Discord bot token is missing.");

        await _client.LoginAsync(TokenType.Bot, _options.Token);
        await _client.StartAsync();

        try
        {
            await Task.Delay(Timeout.Infinite, stoppingToken);
        }
        catch (TaskCanceledException)
        {
            // expected during shutdown
        }
    }

    public override async Task StopAsync(CancellationToken cancellationToken)
    {
        await _client.StopAsync();
        await _client.LogoutAsync();
        await base.StopAsync(cancellationToken);
    }

    private async Task OnReadyAsync()
    {
        using var scope = _services.CreateScope();

        await _interactions.AddModulesAsync(typeof(DiscordBotService).Assembly, scope.ServiceProvider);

        if (_options.GuildId != 0)
        {
            await _interactions.RegisterCommandsToGuildAsync(_options.GuildId, true);
            Console.WriteLine($"Discord slash commands registered to guild {_options.GuildId}");
        }
        else
        {
            await _interactions.RegisterCommandsGloballyAsync(true);
            Console.WriteLine("Discord slash commands registered globally");
        }
    }

    private async Task OnInteractionCreatedAsync(SocketInteraction interaction)
    {
        try
        {
            var context = new SocketInteractionContext(_client, interaction);
            var result = await _interactions.ExecuteCommandAsync(context, _services);

            if (!result.IsSuccess && interaction.Type == InteractionType.ApplicationCommand)
            {
                if (!interaction.HasResponded)
                {
                    await interaction.RespondAsync(
                        $"Command failed: {result.ErrorReason}",
                        ephemeral: true);
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Discord interaction error: {ex}");

            if (!interaction.HasResponded)
            {
                await interaction.RespondAsync(
                    "An unexpected error occurred.",
                    ephemeral: true);
            }
        }
    }

    private static Task LogAsync(LogMessage msg)
    {
        Console.WriteLine($"[Discord] {msg}");
        return Task.CompletedTask;
    }

    public async Task NotifyBuildQueuedAsync(BuildRequest request, CancellationToken ct = default)
    {
        await SendMessageAsync(
            $"Build queued.\nRequested by {request.RequestedBy}\nBuild ID: `{request.Id}`",
            ct);
    }

    public async Task NotifyBuildCompletedAsync(BuildRequest request, CancellationToken ct = default)
    {
        string linksText = request.UploadLinkUrls.Count > 0
            ? string.Join("\n", request.UploadLinkUrls)
            : "*No builds attached.*";

        await SendMessageAsync(
            $"# TRP Auto Build\n<@&{_options.RoleId}> - build completed successfully!\nRequested by {request.RequestedBy}\nBuild ID: `{request.Id}`\n{linksText}",
            ct);
    }

    public async Task NotifyBuildFailedAsync(BuildRequest request, Exception ex, CancellationToken ct = default)
    {
        await SendMessageAsync(
            $"# TRP Auto Build\n<@&{_options.RoleId}> - build failed! ⚠️\nRequested by {request.RequestedBy}\nBuild ID: `{request.Id}`\n```\n{ex.Message}\n```",
            ct);
    }

    private async Task SendMessageAsync(string message, CancellationToken ct)
    {
        if (_options.BuildChannelId == 0)
            return;

        if (_client.ConnectionState != ConnectionState.Connected)
        {
            Console.WriteLine("Discord bot is not connected; skipping notification.");
            return;
        }

        var channel = _client.GetChannel(_options.BuildChannelId) as IMessageChannel;

        if (channel is null)
        {
            Console.WriteLine($"Discord channel not found: {_options.BuildChannelId}");
            return;
        }

        await channel.SendMessageAsync(message);
    }
}