using Core;
using Core.Config;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Drive.v3;
using Google.Apis.Services;
using Google.Apis.Upload;
using Google.Apis.Util.Store;
using Microsoft.Extensions.Options;

namespace GaryBotServer.Steps;

// FILE GENERATED BY CHATGPT -- I can't be bothered here.
public class UploadBuildsStep(WorkspaceManager workspace, IOptions<UploadOptions> options) : IBuildStep
{
    public string Name => "Upload Builds";

    public async Task ExecuteAsync(BuildRequest request, CancellationToken ct)
    {
        request.Status = "Preparing for upload";
        
        string folderId = options.Value.FolderId;

        if (string.IsNullOrWhiteSpace(folderId))
            throw new InvalidOperationException("UploadOptions.FolderId is missing.");

        string buildsFolder = workspace.GetBuildsFolderPath();

        if (!Directory.Exists(buildsFolder))
            throw new DirectoryNotFoundException($"Builds folder not found: {buildsFolder}");

        string[] filesToUpload = Directory.GetFiles(buildsFolder);

        if (filesToUpload.Length == 0)
            throw new InvalidOperationException($"No files found to upload in: {buildsFolder}");

        DriveService drive = await CreateDriveServiceAsync(ct);

        var uploadedFileIds = new HashSet<string>();

        int c = 0;
        foreach (string filePath in filesToUpload)
        {
            c++;
            ct.ThrowIfCancellationRequested();

            request.Status = $"Uploading files ({c} / {filesToUpload.Length})";
            
            var uploaded = await UploadFileAsync(drive, filePath, folderId, ct, request.UploadLinkUrls);
            uploadedFileIds.Add(uploaded.Id);

            Console.WriteLine($"Uploaded: {uploaded.Name} ({uploaded.Id})");
        }

        await DeleteOldFilesAsync(drive, folderId, uploadedFileIds, ct);
    }

    private static async Task<DriveService> CreateDriveServiceAsync(CancellationToken ct)
    {
        string credentialsPath = Path.Combine(AppContext.BaseDirectory, "credentials.json");

        if (!File.Exists(credentialsPath))
            throw new FileNotFoundException(
                $"Google Drive credentials file not found: {credentialsPath}");

        await using var stream = new FileStream(credentialsPath, FileMode.Open, FileAccess.Read);

        var credential = await GoogleWebAuthorizationBroker.AuthorizeAsync(
            GoogleClientSecrets.FromStream(stream).Secrets,
            new[] { DriveService.Scope.Drive },
            "user",
            ct,
            new FileDataStore("DriveApiToken", true));

        return new DriveService(new BaseClientService.Initializer
        {
            HttpClientInitializer = credential,
            ApplicationName = "GaryBotServer Upload Builds"
        });
    }

    private static async Task<Google.Apis.Drive.v3.Data.File> UploadFileAsync(
        DriveService drive,
        string localPath,
        string folderId,
        CancellationToken ct,
        List<string> urls)
    {
        string fileName = Path.GetFileName(localPath);
        string mimeType = GetMimeType(localPath);

        var metadata = new Google.Apis.Drive.v3.Data.File
        {
            Name = fileName,
            Parents = new[] { folderId }
        };

        await using var stream = new FileStream(localPath, FileMode.Open, FileAccess.Read);

        var uploadRequest = drive.Files.Create(metadata, stream, mimeType);
        uploadRequest.Fields = "id, name, createdTime, webViewLink";

        IUploadProgress progress = await uploadRequest.UploadAsync(ct);

        if (progress.Status != UploadStatus.Completed)
        {
            throw new InvalidOperationException(
                $"Failed to upload '{fileName}': {progress.Exception?.Message ?? progress.Status.ToString()}");
        }

        var uploadedFile = uploadRequest.ResponseBody
                           ?? throw new InvalidOperationException($"Upload succeeded but no response for '{fileName}'.");

        // Make it shareable to anyone with the link
        var permission = new Google.Apis.Drive.v3.Data.Permission
        {
            Type = "anyone",
            Role = "reader"
        };

        await drive.Permissions.Create(permission, uploadedFile.Id).ExecuteAsync(ct);

        var url = uploadedFile.WebViewLink;
        urls.Add(url);

        return uploadRequest.ResponseBody;
    }

    private static async Task DeleteOldFilesAsync(
        DriveService drive,
        string folderId,
        HashSet<string> keepFileIds,
        CancellationToken ct)
    {
        string? pageToken = null;

        do
        {
            var listRequest = drive.Files.List();
            listRequest.Q = $"'{folderId}' in parents and trashed = false";
            listRequest.Fields = "nextPageToken, files(id, name)";
            listRequest.PageSize = 1000;
            listRequest.PageToken = pageToken;

            var result = await listRequest.ExecuteAsync(ct);

            foreach (var file in result.Files)
            {
                ct.ThrowIfCancellationRequested();

                if (file.Id is null)
                    continue;

                if (keepFileIds.Contains(file.Id))
                    continue;

                Console.WriteLine($"Deleting old Drive file: {file.Name} ({file.Id})");
                await drive.Files.Delete(file.Id).ExecuteAsync(ct);
            }

            pageToken = result.NextPageToken;
        }
        while (!string.IsNullOrWhiteSpace(pageToken));
    }

    private static string GetMimeType(string path)
    {
        string extension = Path.GetExtension(path).ToLowerInvariant();

        return extension switch
        {
            ".zip" => "application/zip",
            ".txt" => "text/plain",
            ".json" => "application/json",
            ".xml" => "application/xml",
            ".exe" => "application/vnd.microsoft.portable-executable",
            ".dll" => "application/octet-stream",
            ".pdb" => "application/octet-stream",
            ".7z" => "application/x-7z-compressed",
            _ => "application/octet-stream"
        };
    }
}